Repository wanted-all-clear/socialhub, pull requests merged in 2024-08, with the labels that each got.

#13 [Chore] 공통 예외 처리 설정
  .github/pull_request_template.md
  .gitmessage.txt
  docker-compose.yml
  src/main/java/com/allclear/socialhub/common/config/JpaConfig.java
  src/main/java/com/allclear/socialhub/common/config/WebSecurityConfig.java
  src/main/java/com/allclear/socialhub/common/domain/Timestamped.java
  src/main/java/com/allclear/socialhub/common/exception/ErrorCode.java
  src/main/java/com/allclear/socialhub/common/exception/ErrorResponse.java
  src/main/java/com/allclear/socialhub/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/allclear/socialhub/post/controller/PostController.java
  src/main/java/com/allclear/socialhub/post/domain/Post.java
  src/main/java/com/allclear/socialhub/post/dto/PostDto.java
  src/main/java/com/allclear/socialhub/post/repository/PostRepository.java
  src/main/java/com/allclear/socialhub/post/service/PostService.java
  src/main/java/com/allclear/socialhub/user/controller/UserController.java
  src/main/java/com/allclear/socialhub/user/domain/User.java
  src/main/java/com/allclear/socialhub/user/dto/UserDto.java
  src/main/java/com/allclear/socialhub/user/repository/UserRepository.java
  src/main/java/com/allclear/socialhub/user/service/UserService.java
Labels: Chore

#17 [Chore] User 관련 클래스 및 엔티티 생성
  build.gradle
  src/main/java/com/allclear/socialhub/env/EnvConfig.java
  src/main/java/com/allclear/socialhub/user/controller/UserController.java
  src/main/java/com/allclear/socialhub/user/domain/User.java
  src/main/java/com/allclear/socialhub/user/repository/UserRepository.java
  src/main/java/com/allclear/socialhub/user/service/UserService.java
  src/main/java/com/allclear/socialhub/user/type/UserCertifyStatus.java
  src/main/java/com/allclear/socialhub/user/type/UserStatus.java
  src/main/resources/application.yml
  src/test/java/com/allclear/socialhub/user/UserControllerTest.java
  src/test/java/com/allclear/socialhub/user/UserServiceTest.java
Labels: Chore

#18 [Feat] Post 도메인 공통 개발
  src/main/java/com/allclear/socialhub/post/common/hashtag/domain/HashTag.java
  src/main/java/com/allclear/socialhub/post/common/hashtag/domain/PostHashTag.java
  src/main/java/com/allclear/socialhub/post/common/hashtag/repository/HashTagRepository.java
  src/main/java/com/allclear/socialhub/post/common/hashtag/service/HashTagService.java
  src/main/java/com/allclear/socialhub/post/common/like/domain/PostLike.java
  src/main/java/com/allclear/socialhub/post/common/like/repository/PostLikeRepository.java
  src/main/java/com/allclear/socialhub/post/common/share/domain/PostShare.java
  src/main/java/com/allclear/socialhub/post/common/share/repository/PostShareRepository.java
  src/main/java/com/allclear/socialhub/post/common/view/domain/PostView.java
  src/main/java/com/allclear/socialhub/post/common/view/repository/PostViewRepository.java
  src/main/java/com/allclear/socialhub/post/controller/PostController.java
  src/main/java/com/allclear/socialhub/post/domain/Post.java
  src/main/java/com/allclear/socialhub/post/domain/PostType.java
  src/main/java/com/allclear/socialhub/post/repository/PostRepository.java
  src/main/java/com/allclear/socialhub/post/service/PostService.java
Labels: Feat

#23 [Chore] 공통 더미데이터 생성
  src/main/java/com/allclear/socialhub/post/common/like/domain/PostLike.java
  src/main/java/com/allclear/socialhub/post/common/share/domain/PostShare.java
  src/main/java/com/allclear/socialhub/post/common/view/domain/PostView.java
  src/main/java/com/allclear/socialhub/post/domain/Post.java
  src/main/java/com/allclear/socialhub/user/domain/User.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: Fix, Refactor, Chore

#28 ALL-15 환경설정
  src/main/java/com/allclear/socialhub/common/exception/CustomException.java
  src/main/java/com/allclear/socialhub/common/exception/ErrorCode.java
  src/main/java/com/allclear/socialhub/common/exception/ErrorResponse.java
  src/main/java/com/allclear/socialhub/common/exception/handler/GlobalExceptionHandler.java
Labels: Chore

#30 [Fix] querydsl 설정 수정
  build.gradle
Labels: Fix, Chore

#31 [Chore] .gitignore 수정
  .gitignore
Labels: Chore

#32 [Feat] 통계 일자별 API 서비스 로직 구현
  src/main/java/com/allclear/socialhub/post/common/hashtag/repository/HashTagRepository.java
  src/main/java/com/allclear/socialhub/post/common/like/repository/PostLikeRepository.java
  src/main/java/com/allclear/socialhub/post/common/response/StatisticResponse.java
  src/main/java/com/allclear/socialhub/post/common/share/repository/PostShareRepository.java
  src/main/java/com/allclear/socialhub/post/common/view/repository/PostViewRepository.java
  src/main/java/com/allclear/socialhub/post/dto/StatisticDto.java
  src/main/java/com/allclear/socialhub/post/repository/PostRepository.java
  src/main/java/com/allclear/socialhub/post/service/StatisticService.java
  src/main/java/com/allclear/socialhub/post/service/StatisticServiceImpl.java
Labels: Feat

#35 [Feat] 게시물 목록 조회 기능 개발
  src/main/java/com/allclear/socialhub/post/controller/PostController.java
  src/main/java/com/allclear/socialhub/post/dto/PostDto.java
  src/main/java/com/allclear/socialhub/post/dto/PostListResponse.java
  src/main/java/com/allclear/socialhub/post/dto/PostPaging.java
  src/main/java/com/allclear/socialhub/post/repository/PostRepository.java
  src/main/java/com/allclear/socialhub/post/repository/querydsl/PostRepositoryImpl.java
  src/main/java/com/allclear/socialhub/post/repository/querydsl/PostRepositoryQuerydsl.java
  src/main/java/com/allclear/socialhub/post/service/PostService.java
  src/main/java/com/allclear/socialhub/post/service/PostServiceImpl.java
Labels: Feat

#41 [Feat] 통계 시간대별 API 서비스 로직 구현 및 통계 서비스 로직 메서드 통합
  src/main/java/com/allclear/socialhub/post/common/like/repository/PostLikeRepository.java
  src/main/java/com/allclear/socialhub/post/common/share/repository/PostShareRepository.java
  src/main/java/com/allclear/socialhub/post/common/view/repository/PostViewRepository.java
  src/main/java/com/allclear/socialhub/post/controller/StatisticController.java
  src/main/java/com/allclear/socialhub/post/repository/PostRepository.java
  src/main/java/com/allclear/socialhub/post/service/StatisticService.java
  src/main/java/com/allclear/socialhub/post/service/StatisticServiceImpl.java
Labels: Feat, Refactor

#37 [Feat] 사용자 회원가입
  build.gradle
  src/main/java/com/allclear/socialhub/common/config/WebSecurityConfig.java
  src/main/java/com/allclear/socialhub/common/exception/ErrorCode.java
  src/main/java/com/allclear/socialhub/user/controller/UserController.java
  src/main/java/com/allclear/socialhub/user/domain/User.java
  src/main/java/com/allclear/socialhub/user/dto/UserJoinRequest.java
  src/main/java/com/allclear/socialhub/user/dto/UserResponse.java
  src/main/java/com/allclear/socialhub/user/exception/DuplicateUserInfoException.java
  src/main/java/com/allclear/socialhub/user/repository/UserRepository.java
  src/main/java/com/allclear/socialhub/user/service/UserService.java
  src/main/java/com/allclear/socialhub/user/service/UserServiceImpl.java
  src/main/java/com/allclear/socialhub/user/type/UserStatus.java
  src/main/resources/application.yml
  src/test/java/com/allclear/socialhub/user/UserServiceTest.java
Labels: Feat

#39 [Feat] 게시물 등록 기능 개발
  src/main/java/com/allclear/socialhub/common/exception/ErrorCode.java
  src/main/java/com/allclear/socialhub/post/common/hashtag/domain/Hashtag.java
  src/main/java/com/allclear/socialhub/post/common/hashtag/domain/PostHashtag.java
  src/main/java/com/allclear/socialhub/post/common/hashtag/repository/HashTagRepository.java
  src/main/java/com/allclear/socialhub/post/common/hashtag/repository/HashtagRepository.java
  src/main/java/com/allclear/socialhub/post/common/hashtag/repository/PostHashtagRepository.java
  src/main/java/com/allclear/socialhub/post/common/hashtag/service/HashTagService.java
  src/main/java/com/allclear/socialhub/post/common/hashtag/service/HashtagService.java
  src/main/java/com/allclear/socialhub/post/common/hashtag/service/HashtagServiceImpl.java
  src/main/java/com/allclear/socialhub/post/controller/PostController.java
  src/main/java/com/allclear/socialhub/post/domain/Post.java
  src/main/java/com/allclear/socialhub/post/dto/PostCreateRequest.java
  src/main/java/com/allclear/socialhub/post/dto/PostResponse.java
  src/main/java/com/allclear/socialhub/post/repository/querydsl/PostRepositoryImpl.java
  src/main/java/com/allclear/socialhub/post/service/PostService.java
  src/main/java/com/allclear/socialhub/post/service/PostServiceImpl.java
Labels: Feat

#47 [Style] 해시태그 소문자 변경
  src/main/java/com/allclear/socialhub/post/dto/PostResponse.java
  src/main/java/com/allclear/socialhub/post/repository/querydsl/PostRepositoryImpl.java
  src/main/resources/data.sql
Labels: Refactor

#40 [Test] 게시물 등록 기능 테스트
  src/test/java/com/allclear/socialhub/post/service/PostServiceImplTest.java
Labels: Test

#52 [Chore] Swagger 연동 설정
  build.gradle
  src/main/java/com/allclear/socialhub/common/config/SwaggerConfig.java
Labels: Chore

#57 [Feat] 게시물 수정 기능 개발
  src/main/java/com/allclear/socialhub/post/common/hashtag/repository/PostHashtagRepository.java
  src/main/java/com/allclear/socialhub/post/common/hashtag/service/HashtagService.java
  src/main/java/com/allclear/socialhub/post/common/hashtag/service/HashtagServiceImpl.java
  src/main/java/com/allclear/socialhub/post/controller/PostController.java
  src/main/java/com/allclear/socialhub/post/domain/Post.java
  src/main/java/com/allclear/socialhub/post/dto/PostUpdateRequest.java
  src/main/java/com/allclear/socialhub/post/service/PostService.java
  src/main/java/com/allclear/socialhub/post/service/PostServiceImpl.java
Labels: Feat

#45 [Feat] 통계 기능 구현
  build.gradle
  src/main/java/com/allclear/socialhub/common/config/ConverterConfig.java
  src/main/java/com/allclear/socialhub/common/converter/StringToStatisticTypeConverter.java
  src/main/java/com/allclear/socialhub/common/converter/StringToStatisticValueConverter.java
  src/main/java/com/allclear/socialhub/common/exception/ErrorCode.java
  src/main/java/com/allclear/socialhub/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/allclear/socialhub/common/util/DateUtil.java
  src/main/java/com/allclear/socialhub/post/common/hashtag/repository/HashtagRepository.java
  src/main/java/com/allclear/socialhub/post/common/like/repository/PostLikeRepository.java
  src/main/java/com/allclear/socialhub/post/common/response/StatisticQueryResponse.java
  src/main/java/com/allclear/socialhub/post/common/share/repository/PostShareRepository.java
  src/main/java/com/allclear/socialhub/post/common/view/repository/PostViewRepository.java
  src/main/java/com/allclear/socialhub/post/controller/StatisticController.java
  src/main/java/com/allclear/socialhub/post/dto/StatisticRequestParam.java
  src/main/java/com/allclear/socialhub/post/dto/StatisticResponse.java
  src/main/java/com/allclear/socialhub/post/repository/PostRepository.java
  src/main/java/com/allclear/socialhub/post/service/StatisticService.java
  src/main/java/com/allclear/socialhub/post/service/StatisticServiceImpl.java
  src/test/java/com/allclear/socialhub/common/util/DateUtilTest.java
Labels: Feat

#65 [Test] 게시물 목록 조회 기능 테스트
  src/main/java/com/allclear/socialhub/post/dto/PostPaging.java
  src/test/java/com/allclear/socialhub/post/controller/PostControllerTest.java
  src/test/java/com/allclear/socialhub/post/service/PostServiceImplTest.java
Labels: Test

#71 [Feat] 회원가입 비밀번호 암호화 반영
  src/main/java/com/allclear/socialhub/common/config/WebSecurityConfig.java
  src/main/java/com/allclear/socialhub/common/exception/ErrorCode.java
  src/main/java/com/allclear/socialhub/user/domain/User.java
  src/main/java/com/allclear/socialhub/user/service/UserServiceImpl.java
Labels: Feat

#70 [Test] 게시물 등록 기능 테스트
  src/main/java/com/allclear/socialhub/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/allclear/socialhub/post/controller/PostController.java
  src/main/java/com/allclear/socialhub/post/dto/PostCreateRequest.java
  src/test/java/com/allclear/socialhub/post/service/PostServiceImplTest.java
Labels: Test

#76 [Feat] 게시물 좋아요 기능 구현
  src/main/java/com/allclear/socialhub/post/common/like/domain/PostLike.java
  src/main/java/com/allclear/socialhub/post/common/like/dto/PostLikeResponse.java
  src/main/java/com/allclear/socialhub/post/controller/PostController.java
  src/main/java/com/allclear/socialhub/post/domain/Post.java
  src/main/java/com/allclear/socialhub/post/service/PostService.java
  src/main/java/com/allclear/socialhub/post/service/PostServiceImpl.java
Labels: Feat

#78 [Feat] 게시물 공유 기능 구현
  src/main/java/com/allclear/socialhub/post/common/share/domain/PostShare.java
  src/main/java/com/allclear/socialhub/post/common/share/dto/PostShareResponse.java
  src/main/java/com/allclear/socialhub/post/controller/PostController.java
  src/main/java/com/allclear/socialhub/post/domain/Post.java
  src/main/java/com/allclear/socialhub/post/service/PostService.java
  src/main/java/com/allclear/socialhub/post/service/PostServiceImpl.java
Labels: Feat

#88 [Feat] 게시글 삭제 기능 개발
  src/main/java/com/allclear/socialhub/common/exception/ErrorCode.java
  src/main/java/com/allclear/socialhub/post/common/hashtag/service/HashtagService.java
  src/main/java/com/allclear/socialhub/post/common/hashtag/service/HashtagServiceImpl.java
  src/main/java/com/allclear/socialhub/post/common/like/repository/PostLikeRepository.java
  src/main/java/com/allclear/socialhub/post/common/share/repository/PostShareRepository.java
  src/main/java/com/allclear/socialhub/post/common/view/repository/PostViewRepository.java
  src/main/java/com/allclear/socialhub/post/controller/PostController.java
  src/main/java/com/allclear/socialhub/post/dto/PostCreateRequest.java
  src/main/java/com/allclear/socialhub/post/dto/PostUpdateRequest.java
  src/main/java/com/allclear/socialhub/post/service/PostService.java
  src/main/java/com/allclear/socialhub/post/service/PostServiceImpl.java
  src/test/java/com/allclear/socialhub/post/service/PostServiceImplTest.java
Labels: Feat

#83 [Test] 게시물 좋아요 기능 테스트
  src/test/java/com/allclear/socialhub/post/controller/PostControllerTest.java
  src/test/java/com/allclear/socialhub/post/service/PostServiceImplTest.java
Labels: Test

#80 [Feat] 계정 중복 체크
  src/main/java/com/allclear/socialhub/common/exception/ErrorCode.java
  src/main/java/com/allclear/socialhub/common/provider/JwtTokenProvider.java
  src/main/java/com/allclear/socialhub/user/controller/UserController.java
  src/main/java/com/allclear/socialhub/user/service/UserService.java
  src/main/java/com/allclear/socialhub/user/service/UserServiceImpl.java
  src/main/java/com/allclear/socialhub/user/type/UsernameDupStatus.java
  src/test/java/com/allclear/socialhub/post/service/PostServiceImplTest.java
  src/test/java/com/allclear/socialhub/user/UserControllerTest.java
  src/test/java/com/allclear/socialhub/user/UserServiceImplTest.java
Labels: Feat

#95 [Feat] 게시물 검색 기능 개발
  src/main/java/com/allclear/socialhub/common/exception/ErrorCode.java
  src/main/java/com/allclear/socialhub/post/controller/PostController.java
  src/main/java/com/allclear/socialhub/post/domain/SearchByType.java
  src/main/java/com/allclear/socialhub/post/dto/PostListResponse.java
  src/main/java/com/allclear/socialhub/post/repository/querydsl/PostRepositoryImpl.java
  src/main/java/com/allclear/socialhub/post/repository/querydsl/PostRepositoryQuerydsl.java
  src/main/java/com/allclear/socialhub/post/service/PostService.java
  src/main/java/com/allclear/socialhub/post/service/PostServiceImpl.java
Labels: Feat

#97 [Test] 중복된 선언 제거 및 테스트명 수정
  src/test/java/com/allclear/socialhub/post/service/PostServiceImplTest.java
Labels: Test

#100 [Feat] 통계 jwt 인증 기능 개발
  src/main/java/com/allclear/socialhub/post/controller/StatisticController.java
Labels: Feat

#103 [Feat] 통계 jwt 인증 기능 개발
  src/main/java/com/allclear/socialhub/post/controller/StatisticController.java
Labels: Feat

#96 [Feat] 사용자 회원정보 수정
  src/main/java/com/allclear/socialhub/common/exception/ErrorCode.java
  src/main/java/com/allclear/socialhub/common/provider/JwtTokenProvider.java
  src/main/java/com/allclear/socialhub/user/controller/UserController.java
  src/main/java/com/allclear/socialhub/user/domain/User.java
  src/main/java/com/allclear/socialhub/user/dto/UserInfoUpdateRequest.java
  src/main/java/com/allclear/socialhub/user/dto/UserInfoUpdateResponse.java
  src/main/java/com/allclear/socialhub/user/repository/UserRepository.java
  src/main/java/com/allclear/socialhub/user/service/UserService.java
  src/main/java/com/allclear/socialhub/user/service/UserServiceImpl.java
  src/test/java/com/allclear/socialhub/user/UserServiceImplTest.java
Labels: Feat, Test

#104 [Fix] 사용자 회원정보 수정 - 테스트 코드 메서드 변경
  src/main/java/com/allclear/socialhub/common/exception/ErrorCode.java
  src/main/java/com/allclear/socialhub/user/controller/UserController.java
  src/main/java/com/allclear/socialhub/user/repository/UserRepository.java
  src/test/java/com/allclear/socialhub/user/UserServiceImplTest.java
Labels: Fix, Test

#89 [Test] 통계 기능 테스트
  build.gradle
  src/main/java/com/allclear/socialhub/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/allclear/socialhub/common/util/TokenUtil.java
  src/main/java/com/allclear/socialhub/post/service/StatisticServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/allclear/socialhub/common/util/DateUtilTest.java
  src/test/java/com/allclear/socialhub/common/util/TokenUtilTest.java
  src/test/java/com/allclear/socialhub/post/common/hashtag/repository/HashtagRepositoryTest.java
  src/test/java/com/allclear/socialhub/post/common/like/repository/PostLikeRepositoryTest.java
  src/test/java/com/allclear/socialhub/post/common/share/repository/PostShareRepositoryTest.java
  src/test/java/com/allclear/socialhub/post/common/view/repository/PostViewRepositoryTest.java
  src/test/java/com/allclear/socialhub/post/controller/StatisticControllerTest.java
  src/test/java/com/allclear/socialhub/post/repository/PostRepositoryTest.java
  src/test/java/com/allclear/socialhub/post/service/StatisticServiceImplTest.java
  src/test/java/com/allclear/socialhub/post/service/StatisticServiceImplTestHelper.java
  src/test/resources/statistics-data.sql
Labels: Test, Refactor

#86 [Test] 게시물 공유 기능 테스트
  src/main/java/com/allclear/socialhub/post/common/share/dto/PostShareResponse.java
  src/main/java/com/allclear/socialhub/post/service/PostServiceImpl.java
  src/test/java/com/allclear/socialhub/post/controller/PostControllerTest.java
  src/test/java/com/allclear/socialhub/post/service/PostServiceImplTest.java
Labels: Test

#90 [Feat] 게시물 상세 조회 기능 구현
  src/main/java/com/allclear/socialhub/post/controller/PostController.java
  src/main/java/com/allclear/socialhub/post/dto/PostDetailResponse.java
  src/main/java/com/allclear/socialhub/post/repository/querydsl/PostRepositoryImpl.java
  src/main/java/com/allclear/socialhub/post/repository/querydsl/PostRepositoryQuerydsl.java
  src/main/java/com/allclear/socialhub/post/service/PostService.java
  src/main/java/com/allclear/socialhub/post/service/PostServiceImpl.java
Labels: Feat

#92 [Test] 게시물 상세 조회 기능 테스트
  src/test/java/com/allclear/socialhub/post/controller/PostControllerTest.java
  src/test/java/com/allclear/socialhub/post/service/PostServiceImplTest.java
Labels: Test

#109 [Refactor] 게시물 목록 content 글자수 제한 추가
  src/main/java/com/allclear/socialhub/post/controller/PostController.java
  src/main/java/com/allclear/socialhub/post/dto/PostListResponse.java
  src/main/java/com/allclear/socialhub/post/service/PostService.java
Labels: Fix, Refactor

#108 [Fix] UserControllerTest 토큰쪽 테스트 메서드 추가
  src/main/java/com/allclear/socialhub/user/controller/UserController.java
  src/test/java/com/allclear/socialhub/user/UserControllerTest.java
  src/test/java/com/allclear/socialhub/user/UserServiceImplTest.java
Labels: Fix, Test, Refactor

#110 [Refactor] 게시물 유저 토큰 유효성 검증
  src/main/java/com/allclear/socialhub/post/controller/PostController.java
  src/main/java/com/allclear/socialhub/post/dto/PostResponse.java
  src/main/java/com/allclear/socialhub/post/repository/querydsl/PostRepositoryImpl.java
  src/main/java/com/allclear/socialhub/post/repository/querydsl/PostRepositoryQuerydsl.java
  src/main/java/com/allclear/socialhub/post/service/PostService.java
  src/main/java/com/allclear/socialhub/post/service/PostServiceImpl.java
  src/test/java/com/allclear/socialhub/post/controller/PostControllerTest.java
  src/test/java/com/allclear/socialhub/post/service/PostServiceImplTest.java
Labels: Fix, Refactor

#101 [Test] 게시물 검색 기능 테스트
  src/main/java/com/allclear/socialhub/post/service/PostServiceImpl.java
  src/test/java/com/allclear/socialhub/post/service/PostServiceImplTest.java
Labels: Test

#105 [Fix] 중복 계정 있는 경우 테스트 수정
  src/main/java/com/allclear/socialhub/common/config/WebSecurityConfig.java
  src/main/java/com/allclear/socialhub/common/provider/JwtTokenProvider.java
  src/main/java/com/allclear/socialhub/post/controller/StatisticController.java
  src/main/java/com/allclear/socialhub/user/controller/UserController.java
  src/main/java/com/allclear/socialhub/user/dto/UserLoginRequest.java
  src/main/java/com/allclear/socialhub/user/service/UserServiceImpl.java
  src/main/java/com/allclear/socialhub/user/type/UsernameDupStatus.java
  src/test/java/com/allclear/socialhub/user/UserControllerTest.java
  src/test/java/com/allclear/socialhub/user/UserServiceImplTest.java
Labels: Fix, Test

#113 [Docs] README 작성
  README.md
  docs/ERD.png
  docs/Issue.png
  docs/Jira.png
  docs/Notion.png
  docs/img.png
  docs/img_1.png
  docs/img_2.png
  docs/요구사항.png
Labels: Docs

#114 [Refactor] 게시물 상세 조회 시 조회수 1 증가 로직 추가
  src/main/java/com/allclear/socialhub/post/common/view/domain/PostView.java
  src/main/java/com/allclear/socialhub/post/domain/Post.java
  src/main/java/com/allclear/socialhub/post/service/PostServiceImpl.java
  src/test/java/com/allclear/socialhub/post/controller/PostControllerTest.java
Labels: Refactor
